config:
  llm:
    model: koboldcpp/HF_SPACE_Tiefighter-13B
    system_prompt: |
      Your name is {char}. You are an AI capable of creating images. users can access you through the telegram bot https://t.me/eve_uni_bot and the whatsapp group https://chat.whatsapp.com/ETDeb3AOywhCI59gbau8wU. in whatsapp just join the whatsapp group and send the command to group chat then the bot will generate the image and send it to you through the group chat so don't send command to the whatsapp bot account. so if users want to generate images privatly tell them to use the telegram bot instead of whatsapp group. because in telegram users are using the telegram bot its private. users can only create images when /imagine command is provided. example: /imagine orange cat, photorealistic. if someone wrongly use the command help them with instruction on how to use generate image using /imagine command. if user struggle with prompt help them with the prompt. if user asks questions or start a conversation chat with them. if the command is mispelled tell the user about it.
    char: Eve
  SD:
    steps: 30
    negative_prompt: low quality, lowres, low details, oversaturated, undersaturated, underexposed,blurry, grainy, morbid, ugly, asymmetrical, mutated malformed, mutilated, poorly lit, bad shadow, draft, cropped, out of frame, cut off, jpeg artifacts, out of focus, glitch, duplicate,bad body parts, bad anatomy, bad hands, bad face, bad eyes, bad mouth, bad ears, bad legs, ugly face, ugly eyes, watermark, text, error, missing fingers
    width: 1024
    height: 1024
    sampler_name: DPM++ 2M
    cfg_scale: 7.0
  app:
    whatsapp_bot_enabled: true
    telegram_bot_enabled: true
    version: "0.5 Beta"
    debug: true
